# gke-deployment.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-clerk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: clerk-deployment
spec:
  selector:
    matchLabels:
      app: clerk-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: clerk-deployment
    spec:
      volumes:
        - name: pvc-clerk-vol
          persistentVolumeClaim:
            claimName: pvc-clerk
      containers:
        - name: clerk
          image: ucsdcmi/trace-clerk:recent
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 10m
              memory: 80Mi
            requests:
              cpu: 10m
              memory: 80Mi
          ports:
            - containerPort: 5939
              name: "http-server"
          volumeMounts:
            - mountPath: "/usr/share/clerk/data"
              name: pvc-clerk-vol
---
apiVersion: v1
kind: Service
metadata:
  name: trace-clerk
spec:
  ports:
    - name: client
      port: 5939
      targetPort: 5939
  selector:
    app: clerk-deployment
